version: "3"
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./back
    ports:
      - "3000:3000"
    environment:
      - ISSUER_BASE_URL=https://dev-3hmy3galmqfty1xt.us.auth0.com
      - AUDIENCE=https://dott-pc-server.com
      - CLIENT_ORIGIN_URL=https://dott-pc.com.ar/

  python-api:
    build:
      dockerfile: ./Dockerfile
      context: ./python-api
    ports:
      - "5000:5000" # Ajusta el puerto según tu proyecto
    environment:
      - APP_URL=http://backend/api/productos

  dottpc-rabbit:
    container_name: dottpc-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
