version: "3.6"
services:
  dottpc-rabbit:
    container_name: dottpc-rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitnetwork

  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      - MYSQL_ROOT_PASSWORD=M@riano1820
      - MYSQL_DATABASE=dottdb
      - MYSQL_USER=do0tt
      - MYSQL_PASSWORD=M@riano1820
    ports:
      - "3306:3306" # Mapea el puerto de MySQL según sea necesario
    networks:
      - rabbitnetwork

  backend:
    # build:
    #   dockerfile: ./Dockerfile
    #   context: ./back
    image: marianora/dott-back:3.3
    container_name: dott-back
    ports:
      # - "443:3000"
      - "3000:3000"
    environment:
      - ISSUER_BASE_URL=https://dev-3hmy3galmqfty1xt.us.auth0.com
      - AUDIENCE=https://dott-pc-server.com
      - CLIENT_ORIGIN_URL=https://dott-pc.com.ar/
      - RABBIT_MQ_URI=amqp://dottpc-rabbit:5672
      - RABBITMQ_QUEUE=RABBIT_MR_DOTT_QUEUE
      - RABBITMQ_PYTHON_QUEUE=PYTHON_QUEUE
    depends_on:
      - dottpc-rabbit
    networks:
      - rabbitnetwork

  python-api:
    # build:
    #   dockerfile: ./Dockerfile
    #   context: ./python-api
    image: marianora/dott-python:2.4
    container_name: dott-python
    ports:
      - "5000:5000" # Ajusta el puerto según tu proyecto
    environment:
      - RABBITMQ_URL=dottpc-rabbit
      - RABBITMQ_QUEUE=RABBIT_MR_DOTT_QUEUE
      - RABBITMQ_PYTHON_QUEUE=PYTHON_QUEUE
    depends_on:
      - dottpc-rabbit
    networks:
      - rabbitnetwork

networks:
  rabbitnetwork:
    driver: bridge