services:
  dottpc-rabbit:
    container_name: dottpc-rabbit
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitnetwork
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rabbitnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 10

  backend:
    image: marianora/dott-back:latest
    container_name: dott-back
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - rabbitnetwork
    environment:
      - ISSUER_BASE_URL=${ISSUER_BASE_URL}
      - AUDIENCE=${AUDIENCE}
      - CLIENT_ORIGIN_URL=${CLIENT_ORIGIN_URL}
      - ENABLE_HTTPS=${ENABLE_HTTPS}
      - HTTPS_KEY_PATH=${HTTPS_KEY_PATH}
      - HTTPS_CERT_PATH=${HTTPS_CERT_PATH}
      - JWT_AT_SECRET=${JWT_AT_SECRET}
      - JWT_RT_SECRET=${JWT_RT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SYNC=${DB_SYNC}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_PYTHON_QUEUE=${RABBITMQ_PYTHON_QUEUE}
      - RABBIT_MQ_URI=amqp://dottpc-rabbit:5672
    depends_on:
      dottpc-rabbit:
        condition: service_healthy
      mysql:
        condition: service_healthy

  python-api:
    image: marianora/dott-python:latest
    container_name: dott-python
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - rabbitnetwork
    environment:
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_PYTHON_QUEUE=${RABBITMQ_PYTHON_QUEUE}
      - RABBITMQ_RETRY_DELAY=${RABBITMQ_RETRY_DELAY}
      - RABBITMQ_URL=dottpc-rabbit
    depends_on:
      dottpc-rabbit:
        condition: service_healthy

networks:
  rabbitnetwork:
    driver: bridge

volumes:
  mysql_data:
