version: "3"
services:
  mysql:
    build:
      dockerfile: ./Dockerfile
      context: ./dott-database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./back
    ports:
      - "3000:3000"
    environment:
      - ISSUER_BASE_URL=https://dev-3hmy3galmqfty1xt.us.auth0.com
      - AUDIENCE=https://dott-pc-server.com
      - CLIENT_ORIGIN_URL=http://frontend:90/

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./front
      args:
        - AUTH0_DOMAIN=dev-3hmy3galmqfty1xt.us.auth0.com
        - AUTH0_CLIENT_ID=8N7siqdvp5WlxIUNC3hWKR1QiWM92223
        - AUTH0_CALLBACK_URL=http://localhost:90/
        - AUTH0_AUDIENCE=https://dott-pc-server.com
        - API_SERVER_URL=http://localhost:3000
        - PYTHON_API_URL=http://localhost:5000
    ports:
      - "90:4173" # Ajusta el puerto según tu proyecto

  python-api:
    build:
      dockerfile: ./Dockerfile
      context: ./python-api
    ports:
      - "5000:5000" # Ajusta el puerto según tu proyecto
    environment:
      - APP_URL=http://backend:3000/api/productos

volumes:
  mysql-data:
