version: "3"
services:
  mysql:
    build:
      dockerfile: ./Dockerfile
      context: ./dott-database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dottdb

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=localhosst
      - ISSUER_BASE_URL=https://dev-3hmy3galmqfty1xt.us.auth0.com
      - AUDIENCE=https://dott-pc-server.com
      - CLIENT_ORIGIN_URL=http://frontend:90/

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./front
    ports:
      - "80:4173" # Ajusta el puerto según tu proyecto

  python-api:
    build:
      dockerfile: ./Dockerfile
      context: ./python-api
    ports:
      - "5000:5000" # Ajusta el puerto según tu proyecto
    environment:
      - APP_URL=http://backend:3000/api/productos

volumes:
  mysql-data:
