name: Publish python-api image

on:
  push:
    branches: ["main"]      # publica solo al mergear a main
    paths:
      - "python-api/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: ["main"]      # en PR solo construye (sin push)
    paths:
      - "python-api/**"
      - ".github/workflows/python-ci.yml"
  workflow_dispatch:         # opcional: ejecutar manualmente

env:
  # ⚠️ Cambiá esto por tu namespace real de Docker Hub
  DOCKERHUB_NAMESPACE: marianora

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('python-api/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (runtime + dev si aplica)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
    
  build_and_push:
    # si no querés tests, borrá la línea "needs"
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: python-api
            image: python-api            # nombre de la imagen en Docker Hub
            context: python-api          # carpeta del build
            dockerfile: python-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive tags
        id: vars
        run: |
          REPO="${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV
          echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV
          # (Opcional) tag "latest" solo en main:
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "LATEST_TAG=${REPO}:latest" >> $GITHUB_ENV
          fi

      - name: Docker meta (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.name }} image
            org.opencontainers.image.url=https://hub.docker.com/r/${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (PR) / Build & Push (main)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.EDGE_TAG }}
            ${{ env.SHA_TAG }}
            ${{ env.LATEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=max
          provenance: false
          sbom: false
