name: Publish python-api (simple)

on:
  push:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/python-ci.yml"
  workflow_dispatch: {}

env:
  # EDITÁ ESTAS 3 LÍNEAS A TU GUSTO
  DOCKERHUB_NAMESPACE: marianora
  IMAGE_NAME: dott-python
  DOCKERFILE_DIR: python-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build y push usando docker clásico (BuildKit desactivado)
      - name: Build & Push
        env:
          DOCKER_BUILDKIT: 0
        run: |
          set -e
          IMAGE="${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}"
          DOCKERFILE="${{ env.DOCKERFILE_DIR }}/Dockerfile"
          CONTEXT="${{ env.DOCKERFILE_DIR }}"

          echo "Building $IMAGE:latest from $DOCKERFILE (context=$CONTEXT)"
          docker build -f "$DOCKERFILE" -t "$IMAGE:latest" "$CONTEXT"

          echo "Pushing $IMAGE:latest"
          docker push "$IMAGE:latest"
