name: Publish python-api (buildx)

on:
  push:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/python-ci.yml"
  workflow_dispatch: {}

env:
  DOCKERHUB_NAMESPACE: marianora     # <— cambiá si hace falta
  IMAGE_NAME: dott-python            # <— cambiá si hace falta
  DOCKERFILE_DIR: python-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: python-api-build
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # (Opcional) Metadata para labels y auto-tags (sha, fecha, etc.)
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build & Push (Buildx + cache)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
