name: Publish python-api image

on:
  push:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: marianora
  # Toggle rápido para cache GHA (true/false)
  USE_CACHE: "false"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: python-api
            image: python-api
            context: python-api
            dockerfile: python-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx (pinned + debug)
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.2
          driver: docker-container
          buildkitd-flags: --debug
          # ⚠️ IMPORTANTE: una sola línea, sin comentarios ni comillas extra
          driver-opts: image=moby/buildkit:buildx-stable-1


      - name: Derive tags
        id: vars
        run: |
          REPO="${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV
          echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "LATEST_TAG=${REPO}:latest" >> $GITHUB_ENV
          fi

      - name: Docker meta (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.name }} image
            org.opencontainers.image.url=https://hub.docker.com/r/${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      # En PR: build sin push (sin login)
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build con logs "plain" y builder pinneado
      - name: Build (PR) / Build & Push (main)
        uses: docker/build-push-action@v6
        env:
          # Logs detallados para ver el punto de fallo real
          BUILDKIT_PROGRESS: plain
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.EDGE_TAG }}
            ${{ env.SHA_TAG }}
            ${{ env.LATEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          # ⚙️ Caché GHA: desactivada por defecto; activala poniendo USE_CACHE="true"
          cache-from: ${{ env.USE_CACHE == 'true' && format('type=gha,scope={0}', matrix.name) || '' }}
          cache-to: ${{ env.USE_CACHE == 'true' && format('type=gha,scope={0},mode=max', matrix.name) || '' }}
          provenance: false
          sbom: false
