name: Build and Publish images

on:
  push:
    branches:
      - main
    paths:
      - 'python-api/**'
      - '.github/workflows/python-ci.yml'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push python-api
        run: |
          docker build ./python-api \
            -f ./python-api/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/dott-python:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dott-python:latest

      # Si querés otro servicio (ejemplo front-end), duplicás el bloque:
      # - name: Build & Push front-end
      #   run: |
      #     docker build ./front-end-nextjs \
      #       -f ./front-end-nextjs/Dockerfile \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/dott-frontend:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/dott-frontend:latest
