name: CI (build & scan)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  DOCKERHUB_NAMESPACE: miusuario          # <--- CAMBIÁ por tu user/org de Docker Hub
  PLATFORMS: linux/amd64
  CACHE_MODE: max
  TRIVY_SEVERITY: CRITICAL
  TRIVY_IGNORE_UNFIXED: true

jobs:
  # Dejamos un job "lint_test" minimal por si en el futuro sumás tests.
  lint_test:
    name: (Opcional) Tests (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    matrix:
      include:
        - name: back
          context: back
          type: node
          node_version: "20"
          lint_cmd: ""       # <- sin ESLint
          test_cmd: ""       # <- sin tests (ajustá cuando tengas)
        - name: dott-front
          context: dott-front
          type: node
          node_version: "20"
          lint_cmd: ""
          test_cmd: ""
        - name: python-api
          context: python-api
          type: python
          python_version: "3.9"  # <- compat con tus pins
          lint_cmd: ""           # p/ahora sin flake8
          test_cmd: ""           # p/ahora sin pytest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Python (solo se setea si lo usás más adelante)
      - name: Setup Python
        if: matrix.type == 'python' && (matrix.lint_cmd != '' || matrix.test_cmd != '')
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
          cache-dependency-path: |
            ${{ matrix.context }}/requirements.txt
            ${{ matrix.context }}/requirements-dev.txt

      - name: Install deps (Python)
        if: matrix.type == 'python' && (matrix.lint_cmd != '' || matrix.test_cmd != '')
        working-directory: ${{ matrix.context }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      # Node (solo si algún día activás tests/lint)
      - name: Setup Node
        if: matrix.type == 'node' && (matrix.lint_cmd != '' || matrix.test_cmd != '')
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.context }}/package-lock.json

      - name: Install deps (Node)
        if: matrix.type == 'node' && (matrix.lint_cmd != '' || matrix.test_cmd != '')
        working-directory: ${{ matrix.context }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Lint
        if: matrix.lint_cmd != ''
        working-directory: ${{ matrix.context }}
        run: ${{ matrix.lint_cmd }}

      - name: Test
        if: matrix.test_cmd != ''
        working-directory: ${{ matrix.context }}
        run: ${{ matrix.test_cmd }}

  build_scan_push:
    name: Build, Scan & (Push en main) (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: [ lint_test ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: back
            context: back
            dockerfile: back/Dockerfile
          - name: dott-front
            context: dott-front
            dockerfile: dott-front/Dockerfile
          - name: python-api
            context: python-api
            dockerfile: python-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive tags & flags
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          REPO="${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.name }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TAGS="${REPO}:pr-${{ github.event.pull_request.number }}-${GITHUB_SHA::7}"
            PUSH=false
            SCAN_REF="${TAGS}"
          else
            TAGS="${REPO}:edge
          ${REPO}:${GITHUB_SHA::7}"
            PUSH=true
            SCAN_REF="${REPO}:${GITHUB_SHA::7}"
          fi
          echo "IMAGE_REPO=${REPO}" >> $GITHUB_ENV
          printf "TAGS<<EOF\n%s\nEOF\n" "${TAGS}" >> $GITHUB_ENV
          echo "PUSH=${PUSH}" >> $GITHUB_ENV
          echo "SCAN_REF=${SCAN_REF}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta (labels OCI)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false
          labels: |
            org.opencontainers.image.title=${{ matrix.name }}
            org.opencontainers.image.description=${{ matrix.name }} image
            org.opencontainers.image.url=https://hub.docker.com/r/${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.name }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Login to Docker Hub (only on main)
        if: env.PUSH == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build local (load) para escanear antes de publicar
      - name: Build (load) for scan
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          load: true
          push: false
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=${{ env.CACHE_MODE }}

      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ env.SCAN_REF }}
          severity: ${{ env.TRIVY_SEVERITY }}
          ignore-unfixed: ${{ env.TRIVY_IGNORE_UNFIXED }}
          vuln-type: 'os,library'
          format: 'table'
          exit-code: '1'

      - name: Build & Push (main)
        if: env.PUSH == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=${{ env.CACHE_MODE }}
