name: Build Publish Backend

on:
  push:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKERHUB_NAMESPACE: marianora

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolver namespace
        id: ns
        run: |
          NS="${{ github.event.inputs.dockerhub_namespace || vars.DOCKERHUB_NAMESPACE || env.DOCKERHUB_NAMESPACE }}"
          echo "namespace=$NS" >> "$GITHUB_OUTPUT"

      - name: Derive image coordinates & tags base
        run: |
          REPO="${{ steps.ns.outputs.namespace }}/dott-python"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          fi

          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            echo "SEMVER_TAG=${REPO}:${VERSION#v}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub (solo si se va a pushear)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

            # (Opcional pero recomendable) Loguearse antes del pull para evitar rate limit
      - name: Login to Docker Hub (antes del build)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Pre-pull con reintentos: evita EOF al descargar la base
      - name: Pre-pull base image (retry)
        run: |
          for i in 1 2 3 4 5; do
            echo "Pull intento $i..."
            docker pull python:3.11-alpine && exit 0
            sleep $((5*i))
          done
          echo "Fallo el pull luego de varios intentos" >&2
          exit 1
      
      # 👇 Build clásico (sin BuildKit) + push
      - name: Build & Push con Docker clásico (sin BuildKit)
        env:
          DOCKER_BUILDKIT: "0"         # fuerza el builder legacy → no usa buildx/buildkit
        run: |
          set -euo pipefail
      
          # Asegurá que IMAGE_REPO y tags ya estén seteados en pasos previos (ns/vars)
          TAGS="-t ${IMAGE_REPO}:${GITHUB_SHA::7}"
          [ -n "${EDGE_TAG:-}" ] && TAGS="$TAGS -t ${EDGE_TAG}"
          [ -n "${SEMVER_TAG:-}" ] && TAGS="$TAGS -t ${SEMVER_TAG}"
      
          echo "Construyendo con: $TAGS"
          docker build $TAGS -f "${{ matrix.dockerfile }}" "${{ matrix.context }}"
      
          # En PR no pusheamos
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            docker push "${IMAGE_REPO}:${GITHUB_SHA::7}"
            [ -n "${EDGE_TAG:-}" ] && docker push "${EDGE_TAG}"
            [ -n "${SEMVER_TAG:-}" ] && docker push "${SEMVER_TAG}"
          fi

