name: Build Publish Backend

on:
  push:
    branches: ["main"]                # publica solo al mergear a main
    paths:
      - "python-api/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:                  # ejecutar manualmente
    inputs:
      dockerhub_namespace:
        description: "Namespace de Docker Hub"
        required: false
        default: "marianora"

permissions:
  contents: read

env:
  # Valor por defecto. Podés sobreescribirlo con:
  #  - Input del workflow_dispatch
  #  - Variable del repo: Settings → Variables → Actions → DOCKERHUB_NAMESPACE
  DOCKERHUB_NAMESPACE: marianora

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: python-api
            image: dott-python
            context: python-api
            dockerfile: python-api/Dockerfile
            cache_scope: python-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolver namespace
        id: ns
        env:
          IN_NS: ${{ github.event.inputs.dockerhub_namespace }}
          VAR_NS: ${{ vars.DOCKERHUB_NAMESPACE }}
          ENV_NS: ${{ env.DOCKERHUB_NAMESPACE }}
        run: |
          NS="${IN_NS:-${VAR_NS:-${ENV_NS}}}"
          echo "namespace=$NS" >> "$GITHUB_OUTPUT"
          echo "Usando NAMESPACE=$NS"

      - name: Set up QEMU (opcional multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx (pinned buildkit)
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.14.2
          buildkitd-flags: --debug
      
      - name: Build (PR) o Build & Push (main/tags)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          no-cache: false
          tags: |
            ${{ env.SHA_TAG }}
            ${{ env.EDGE_TAG }}
            ${{ env.SEMVER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.cache_scope }}
          cache-to: type=gha,scope=${{ matrix.cache_scope }},mode=max
          provenance: false
          sbom: false


      - name: Derive image coordinates & tags base
        id: vars
        run: |
          REPO="${{ steps.ns.outputs.namespace }}/${{ matrix.image }}"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV

          # Siempre tag por SHA corto
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV

          # 'edge' solo en push a main
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          else
            echo "EDGE_TAG=" >> $GITHUB_ENV
          fi

          # Si es un tag (vX.Y.Z), usarlo como tag semántico
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"       # ej: v1.2.3
            echo "SEMVER_TAG=${REPO}:${VERSION#v}" >> $GITHUB_ENV  # 1.2.3 (sin la 'v')
          else
            echo "SEMVER_TAG=" >> $GITHUB_ENV
          fi

      - name: Docker meta (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.name }} image
            org.opencontainers.image.url=https://hub.docker.com/r/${{ steps.ns.outputs.namespace }}/${{ matrix.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Login to Docker Hub (solo si se va a pushear)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (PR) o Build & Push (main/tags)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          # Descomentar para multi-arch:
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.SHA_TAG }}
            ${{ env.EDGE_TAG }}
            ${{ env.SEMVER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.cache_scope }}
          cache-to: type=gha,scope=${{ matrix.cache_scope }},mode=max
          provenance: false
          sbom: false


          
