name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_test:
    name: (Opcional) Tests (${{ matrix.name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: back
            context: back
            type: node
            node_version: "20"
            lint_cmd: ""
            test_cmd: ""
          - name: dott-front
            context: dott-front
            type: node
            node_version: "20"
            lint_cmd: ""
            test_cmd: ""
          - name: python-api
            context: python-api
            type: python
            python_version: "3.9"
            lint_cmd: ""
            test_cmd: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build_scan_push:
    name: Build, Scan & (Push en main) (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: [ lint_test ]

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: back
            context: back
            dockerfile: back/Dockerfile
          - name: dott-front
            context: dott-front
            dockerfile: dott-front/Dockerfile
          - name: python-api
            context: python-api
            dockerfile: python-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive tags & flags
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          REPO="${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.name }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TAGS="${REPO}:pr-${{ github.event.pull_request.number }}-${GITHUB_SHA::7}"
            PUSH=false
            SCAN_REF="${TAGS}"
          else
            TAGS="${REPO}:edge
          ${REPO}:${GITHUB_SHA::7}"
            PUSH=true
            SCAN_REF="${REPO}:${GITHUB_SHA::7}"
          fi
          echo "IMAGE_REPO=${REPO}" >> $GITHUB_ENV
          printf "TAGS<<EOF\n%s\nEOF\n" "${TAGS}" >> $GITHUB_ENV
          echo "PUSH=${PUSH}" >> $GITHUB_ENV
          echo "SCAN_REF=${SCAN_REF}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false

      - name: Login to Docker Hub (only on main)
        if: env.PUSH == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (load) for scan
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          load: true
          push: false
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=max

      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ env.SCAN_REF }}
          severity: CRITICAL
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'table'
          exit-code: '1'

      - name: Build & Push (main)
        if: env.PUSH == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=max
