name: Publish images

on:
  push:
    branches: ["main"]      # publica solo al mergear a main
  workflow_dispatch:        # opcional: disparo manual

env:
  DOCKERHUB_NAMESPACE: marianora

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: back
            image: dott-back
            context: back
            dockerfile: back/Dockerfile
          - name: python-api
            image: dott-python
            context: python-api
            dockerfile: python-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Builder del daemon: más estable en GHA que docker-container
      - name: Set up Buildx (daemon)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true

      - name: Derive tags
        id: vars
        run: |
          REPO="${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV
          echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker meta (labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: latest=false
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.name }} image
            org.opencontainers.image.url=https://hub.docker.com/r/${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      # Login ANTES del build para evitar rate limit al tirar la base
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          pull: true
          push: true
          tags: |
            ${{ env.EDGE_TAG }}
            ${{ env.SHA_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=max
          provenance: false
          sbom: false
