name: Build Publish Backend

on:
  push:
    branches: ["main"]
    paths:
      - "python-api/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKERHUB_NAMESPACE: marianora

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolver namespace
        id: ns
        run: |
          NS="${{ github.event.inputs.dockerhub_namespace || vars.DOCKERHUB_NAMESPACE || env.DOCKERHUB_NAMESPACE }}"
          echo "namespace=$NS" >> "$GITHUB_OUTPUT"

      - name: Derive image coordinates & tags base
        run: |
          REPO="${{ steps.ns.outputs.namespace }}/dott-python"
          echo "IMAGE_REPO=$REPO" >> $GITHUB_ENV
          echo "SHA_TAG=${REPO}:${GITHUB_SHA::7}" >> $GITHUB_ENV

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "EDGE_TAG=${REPO}:edge" >> $GITHUB_ENV
          fi

          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            echo "SEMVER_TAG=${REPO}:${VERSION#v}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub (solo si se va a pushear)
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push con Docker nativo
        run: |
          TAGS="-t ${{ env.SHA_TAG }}"
          [ -n "${EDGE_TAG}" ] && TAGS="$TAGS -t ${EDGE_TAG}"
          [ -n "${SEMVER_TAG}" ] && TAGS="$TAGS -t ${SEMVER_TAG}"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            docker build $TAGS -f python-api/Dockerfile python-api
          else
            docker build $TAGS -f python-api/Dockerfile python-api
            docker push --all-tags ${{ env.IMAGE_REPO }}
          fi
