name: Build and Push Docker Image

env:
  DOCKER_IMAGE_NAME: marianora/dott-python
  DOCKER_REGISTRY: docker.io

on:
  push:
    branches: ["main"]                # publica solo al mergear a main
    paths:
      - "python-api/**"
      - ".github/workflows/test.yml"
      
jobs:
  build-and-push:
    name: Build and Push python-api Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push image (python-api)
        uses: docker/build-push-action@v6
        with:
          context: ./python-api
          file: ./python-api/Dockerfile
          # platforms: linux/amd64,linux/arm64   # <- opcional multi-arch
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
